version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - './nginx.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '80:80'
    networks:
      - ai-dating-network
    depends_on:
      - ai-dating
  ai-dating:
    build: .
    container_name: ai-dating
    image: ai-dating
    ports:
      - "8001:5000"
    volumes:
      - ./:/app/
    networks:
      ai-dating-network:
        aliases:
          - ai-dating-app
    env_file:
    - path: ./default.env
      required: true
    - path: ./.env.local
      required: false
  db:
    image: postgres:13
    container_name: db
    volumes:
      - dbdata:/var/lib/postgresql/data/
    networks:
      ai-dating-network:
    environment:
      - POSTGRES_USER=ai_dating
      - POSTGRES_PASSWORD=ai_dating
      - POSTGRES_DB=ai_dating_dev
    ports:
      - "5432:5432"
    expose:
      - 5432

volumes:
  dbdata:

networks:
  ai-dating-network:
