version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - './nginx.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '80:80'
    networks:
      - ai-dating-network
    depends_on:
      - ai-dating
  ai-dating:
    build: .
    container_name: ai-dating
    command: gunicorn --bind 0.0.0.0:8001 --workers 4 "src.app:create_app()"
    image: ai-dating
    ports:
      - "8001:5000"
    volumes:
      - type: bind
        source: ./
        target: /app/
    networks:
      ai-dating-network:
        aliases:
          - ai-dating-app

networks:
  ai-dating-network:


